// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGoPD18ID6X6G6RMtPilx_rtoqn-2La18',
    appId: '1:750152695490:web:bda20a152df9513e17055b',
    messagingSenderId: '750152695490',
    projectId: 'chat-app-e72dd',
    authDomain: 'chat-app-e72dd.firebaseapp.com',
    storageBucket: 'chat-app-e72dd.appspot.com',
    measurementId: 'G-RN381916VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwVr7kpc8vbEwGruXYyyhb1xmQ_5EDRCI',
    appId: '1:750152695490:android:e3d5f65222e4a9ea17055b',
    messagingSenderId: '750152695490',
    projectId: 'chat-app-e72dd',
    storageBucket: 'chat-app-e72dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK4-W4QCDlAB6mynPq3SJbdFS-W_7D4tM',
    appId: '1:750152695490:ios:517bf243a97c0fdc17055b',
    messagingSenderId: '750152695490',
    projectId: 'chat-app-e72dd',
    storageBucket: 'chat-app-e72dd.appspot.com',
    iosBundleId: 'com.example.scholarChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK4-W4QCDlAB6mynPq3SJbdFS-W_7D4tM',
    appId: '1:750152695490:ios:517bf243a97c0fdc17055b',
    messagingSenderId: '750152695490',
    projectId: 'chat-app-e72dd',
    storageBucket: 'chat-app-e72dd.appspot.com',
    iosBundleId: 'com.example.scholarChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGoPD18ID6X6G6RMtPilx_rtoqn-2La18',
    appId: '1:750152695490:web:c9283ab44fcb4bcf17055b',
    messagingSenderId: '750152695490',
    projectId: 'chat-app-e72dd',
    authDomain: 'chat-app-e72dd.firebaseapp.com',
    storageBucket: 'chat-app-e72dd.appspot.com',
    measurementId: 'G-N260X88LSZ',
  );
}
